### PR TITLE
feat(preset): added another preset for #3

### PR DESCRIPTION
**Pull request by bahmutov**
I am testing the simple preset differently from Angular - it is simpler to just give it parsed commits and confirm the result.

### CODE REVIEW

**Comment by stevemao** [comment]
I was actually going to remove `preset` since everyone is just using angular... Is this related to https://github.com/conventional-changelog/conventional-recommended-bump/issues/4?

**Comment by bahmutov** [comment]
I am not convinced a patch is always needed, especially for chores. Angular config aside, I prefer to use semantic tags `chore(docs):...` but not release them as new package versions to avoid noise. Having this preset would work nicely with my default "simple" commit check in [pre-git](https://github.com/bahmutov/pre-git)

**Comment by stevemao** [comment]
We can bikeshed this. Definitely removing `preset`. We can probably add a flag to config or return a `confidence` field.

**Comment by hutson** [comment]
@stevemao @bahmutov using a configuration file to drive the choice of preset is being discussed in conventional-changelog/conventional-changelog/issues/195

In the meantime, @stevemao what do you think of having @bahmutov re-file this enhancement against the `conventional-recommended-bump` package in the `conventional-changelog` monorepo?
 (https://github.com/conventional-changelog/conventional-changelog)

I'd like to see users have access to another awesome preset for their projects!

**Comment by hutson** [comment]
I've been given permissions to close out issues and pull requests for the purpose of moving discussions over to the `conventional-changelog` monorepo.

In the meantime, as I mentioned in my previous comment, while the community is discussing how to move forward with support for per-project configuration files, and the proper behavior for the `preset` option, I'd like to encourage you, @bahmutov, to re-submit this enhancement to `conventional-recommended-bump` within the `conventional-changelog` monorepo if you would find value in these changes in near future.

**Pull request closed without merging**
